/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        solarized: {
          base03: 'var(--color-solarized-base03)',
          base02: 'var(--color-solarized-base02)',
          base01: 'var(--color-solarized-base01)',
          base00: 'var(--color-solarized-base00)',
          base0: 'var(--color-solarized-base0)',
          base1: 'var(--color-solarized-base1)',
          base2: 'var(--color-solarized-base2)',
          base3: 'var(--color-solarized-base3)',
          yellow: 'var(--color-solarized-yellow)',
          orange: 'var(--color-solarized-orange)',
          red: 'var(--color-solarized-red)',
          magenta: 'var(--color-solarized-magenta)',
          violet: 'var(--color-solarized-violet)',
          blue: 'var(--color-solarized-blue)',
          cyan: 'var(--color-solarized-cyan)',
          green: 'var(--color-solarized-green)',
        },
        gaming: {
          base: 'var(--color-bg-base)',
          card: 'var(--color-bg-card)',
          border: 'var(--color-border)',
        },
        surface: {
          base: 'var(--color-surface-base)',
          card: 'var(--color-surface-card)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
        },
        content: {
          primary: 'var(--color-content-primary)',
          secondary: 'var(--color-content-secondary)',
          muted: 'var(--color-content-muted)',
        },
        line: 'var(--color-line)',
        tone: {
          muted: 'var(--color-tone-muted)',
          info: 'var(--color-tone-info)',
          success: 'var(--color-tone-success)',
          warning: 'var(--color-tone-warning)',
          danger: 'var(--color-tone-danger)',
          accent: 'var(--color-tone-accent)',
          special: 'var(--color-tone-special)',
        },
        status: {
          locked: 'var(--color-status-locked)',
          completed: 'var(--color-status-completed)',
          campfire: 'var(--color-status-campfire)',
          quest: 'var(--color-status-quest)',
          boss: 'var(--color-status-boss)',
          danger: 'var(--color-status-danger)',
        },
        accent: {
          scholar: 'var(--color-accent-scholar)',
          champion: 'var(--color-accent-champion)',
          guide: 'var(--color-accent-guide)',
          specialist: 'var(--color-accent-specialist)',
          neutral: 'var(--color-accent-neutral)',
        },
      },
      boxShadow: {
        'glow-primary': 'var(--shadow-glow-primary)',
        'glow-gold': 'var(--shadow-glow-gold)',
        dock: 'var(--shadow-dock)',
        'inset-highlight': 'var(--shadow-inset-highlight)',
        marker: 'var(--shadow-marker)',
      },
      fontFamily: {
        display: ['Outfit', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
    },
  },
  daisyui: {
    themes: [
      {
        dark: {
          primary: 'var(--color-tone-accent)',
          'primary-content': 'var(--color-surface-base)',
          secondary: 'var(--color-tone-info)',
          'secondary-content': 'var(--color-surface-base)',
          accent: 'var(--color-tone-warning)',
          'accent-content': 'var(--color-surface-base)',
          neutral: 'var(--color-surface-card)',
          'neutral-content': 'var(--color-content-primary)',
          'base-100': 'var(--color-surface-base)',
          'base-200': 'var(--color-surface-card)',
          'base-300': 'var(--color-line)',
          'base-content': 'var(--color-content-primary)',
          info: 'var(--color-tone-info)',
          'info-content': 'var(--color-surface-base)',
          success: 'var(--color-tone-success)',
          'success-content': 'var(--color-surface-base)',
          warning: 'var(--color-tone-warning)',
          'warning-content': 'var(--color-surface-base)',
          error: 'var(--color-tone-danger)',
          'error-content': 'var(--color-surface-base)',
        },
      },
      {
        light: {
          primary: 'var(--color-tone-accent)',
          'primary-content': 'var(--color-surface-base)',
          secondary: 'var(--color-tone-info)',
          'secondary-content': 'var(--color-surface-base)',
          accent: 'var(--color-tone-warning)',
          'accent-content': 'var(--color-surface-base)',
          neutral: 'var(--color-surface-card)',
          'neutral-content': 'var(--color-content-primary)',
          'base-100': 'var(--color-surface-base)',
          'base-200': 'var(--color-surface-card)',
          'base-300': 'var(--color-line)',
          'base-content': 'var(--color-content-primary)',
          info: 'var(--color-tone-info)',
          'info-content': 'var(--color-surface-base)',
          success: 'var(--color-tone-success)',
          'success-content': 'var(--color-surface-base)',
          warning: 'var(--color-tone-warning)',
          'warning-content': 'var(--color-surface-base)',
          error: 'var(--color-tone-danger)',
          'error-content': 'var(--color-surface-base)',
        },
      },
    ],
  },
  plugins: [require('daisyui')],
};
