name = "eduquest-backend"
main = "src/index.ts"
compatibility_date = "2026-05-30"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "apti.space/api/*", zone_name = "apti.space" }
]

[vars]
APP_ENV = "production"
FRONTEND_URL = "https://apti.space"
ASSET_PUBLIC_BASE_URL = "https://apti.space/api/public-assets"
GITHUB_REDIRECT_URI = "https://apti.space/api/auth/github/callback"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "eduquest-assets"

[[d1_databases]]
binding = "DB"
database_name = "eduquest-db"
database_id = "1ce0d4a5-8d05-4a89-9fe5-98320788a2de"
migrations_dir = "src/db/d1-migrations"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
